In [ ]:
import torch
import torch.nn as nn
class Mylinearmodel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)
    return out





In [ ]:
##create the data
num_features = torch.rand(10,5)

#making the model

model = Mylinearmodel(num_features.shape[1])

###call model for forward pass
model(num_features)


tensor([[0.5201],
        [0.4391],
        [0.4431],
        [0.5107],
        [0.3808],
        [0.4601],
        [0.4578],
        [0.4818],
        [0.5063],
        [0.5561]], grad_fn=<SigmoidBackward0>)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Mylinearmodel                            [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Mynewmodel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.artitecture = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, num_features):
    out = self.artitecture(num_features)
    return out


In [ ]:
num_features = torch.rand(15,10)

In [ ]:
model = Mynewmodel(num_features.shape[1])
model(num_features)

tensor([[0.4760],
        [0.4795],
        [0.4828],
        [0.4499],
        [0.4903],
        [0.4719],
        [0.4830],
        [0.4618],
        [0.4846],
        [0.4771],
        [0.4649],
        [0.4619],
        [0.4542],
        [0.4894],
        [0.4650]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, (15,10))

Layer (type:depth-idx)                   Output Shape              Param #
Mynewmodel                               [15, 1]                   --
├─Sequential: 1-1                        [15, 1]                   --
│    └─Linear: 2-1                       [15, 3]                   33
│    └─ReLU: 2-2                         [15, 3]                   --
│    └─Linear: 2-3                       [15, 1]                   4
│    └─Sigmoid: 2-4                      [15, 1]                   --
Total params: 37
Trainable params: 37
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [243]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch import optim

In [216]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [217]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [218]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [219]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [220]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [221]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [222]:
y_train

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,

In [223]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [224]:
X_train_tensor.shape

torch.Size([455, 30])

In [225]:
y_train_tensor.shape

torch.Size([455])

In [226]:
type(X_train_tensor)

torch.Tensor

In [233]:
class Mysimplemodel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.Linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.Linear(features)
    out = self.sigmoid(out)
    return out


In [234]:
learning_rate = 0.1
epochs = 25

In [245]:
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [246]:
# create model
model = Mysimplemodel(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5456297993659973
Epoch: 2, Loss: 0.5456297993659973
Epoch: 3, Loss: 0.5456297993659973
Epoch: 4, Loss: 0.5456297993659973
Epoch: 5, Loss: 0.5456297993659973
Epoch: 6, Loss: 0.5456297993659973
Epoch: 7, Loss: 0.5456297993659973
Epoch: 8, Loss: 0.5456297993659973
Epoch: 9, Loss: 0.5456297993659973
Epoch: 10, Loss: 0.5456297993659973
Epoch: 11, Loss: 0.5456297993659973
Epoch: 12, Loss: 0.5456297993659973
Epoch: 13, Loss: 0.5456297993659973
Epoch: 14, Loss: 0.5456297993659973
Epoch: 15, Loss: 0.5456297993659973
Epoch: 16, Loss: 0.5456297993659973
Epoch: 17, Loss: 0.5456297993659973
Epoch: 18, Loss: 0.5456297993659973
Epoch: 19, Loss: 0.5456297993659973
Epoch: 20, Loss: 0.5456297993659973
Epoch: 21, Loss: 0.5456297993659973
Epoch: 22, Loss: 0.5456297993659973
Epoch: 23, Loss: 0.5456297993659973
Epoch: 24, Loss: 0.5456297993659973
Epoch: 25, Loss: 0.5456297993659973


In [247]:
model.Linear.bias

Parameter containing:
tensor([-0.0556], requires_grad=True)

In [248]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6100338697433472
